#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
generate_security_description.py

Use the SiliconFlow chat-completions API to generate conservative natural-language
security descriptions from screened vulnerability paths.

Input:
    outputs/{dataset}/vul_paths/train.vul_paths.jsonl
    outputs/{dataset}/vul_paths/valid.vul_paths.jsonl
    outputs/{dataset}/vul_paths/test.vul_paths.jsonl

Output:
    outputs/{dataset}/descriptions_llm/train.desc.jsonl
    outputs/{dataset}/descriptions_llm/valid.desc.jsonl
    outputs/{dataset}/descriptions_llm/test.desc.jsonl

Example:

python src/generate_security_description.py ^
  --input_dir outputs/lin_et_al/vul_paths ^
  --output_dir outputs/lin_et_al/descriptions_llm ^
  --code_key func ^
  --splits train,valid,test
"""

import argparse
import json
import os
import re
import time
from typing import Any, Dict, List, Optional

import requests

try:
    from tqdm import tqdm
except ImportError:
    tqdm = lambda x, **kwargs: x


API_BASE_URL_DEFAULT = "https://api.siliconflow.cn/v1/chat/completions"
API_MODEL_DEFAULT = "Qwen/Qwen3-Coder-30B-A3B-Instruct"


# =============================
# JSONL utils
# =============================

def read_jsonl(path: str):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def write_jsonl(path: str, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def clean_text(text: Any, max_chars: int = 4000) -> str:
    if text is None:
        return ""
    text = str(text)
    text = " ".join(text.replace("\n", " ").replace("\t", " ").split())
    if len(text) > max_chars:
        return text[:max_chars] + " ..."
    return text


def has_real_vul_path(row: Dict[str, Any]) -> bool:
    """
    Return True only when this sample has a real vulnerability-oriented path.

    False cases:
    - vul_path_text is empty
    - vul_path_text is exactly/essentially <VUL_PATH> none </VUL_PATH>
    - vul_paths is an empty list

    This is used to avoid calling the LLM for no-evidence samples.
    """
    vul_path_text = clean_text(row.get("vul_path_text", ""), max_chars=4000)
    normalized = vul_path_text.lower().replace(" ", "")

    if normalized in {
        "",
        "none",
        "<vul_path>none</vul_path>",
        "<vul_path_text><vul_path>none</vul_path></vul_path_text>",
    }:
        return False

    if "<vul_path>none</vul_path>" in normalized:
        return False

    vul_paths = row.get("vul_paths", None)
    if isinstance(vul_paths, list) and len(vul_paths) == 0:
        return False

    # Real path text generated by 01 usually contains these fields.
    lower_text = vul_path_text.lower()
    if "type:" in lower_text or "sink:" in lower_text or "risk:" in lower_text:
        return True

    # If structured vul_paths exists and is non-empty, regard it as real evidence.
    if isinstance(vul_paths, list) and len(vul_paths) > 0:
        return True

    return False


def find_input_file(input_dir: str, split: str) -> Optional[str]:
    candidates = [
        os.path.join(input_dir, f"{split}.vul_paths.jsonl"),
        os.path.join(input_dir, f"{split}.jsonl"),
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return None


# =============================
# Prompt construction
# =============================

def build_prompt(row: Dict[str, Any], code_key: str = "func", max_code_chars: int = 3500, max_path_chars: int = 2000) -> List[Dict[str, str]]:
    code = clean_text(row.get(code_key, ""), max_chars=max_code_chars)
    vul_path_text = clean_text(row.get("vul_path_text", ""), max_chars=max_path_chars)

    if not vul_path_text:
        vul_paths = row.get("vul_paths", [])
        vul_path_text = clean_text(json.dumps(vul_paths, ensure_ascii=False), max_chars=max_path_chars)

    evidence_status = "HAS_REAL_VUL_PATH" if has_real_vul_path(row) else "NO_REAL_VUL_PATH"

    system_prompt = (
        "You are a C/C++ security analysis assistant. "
        "Your task is to generate a concise and factual security description based only on the given code and extracted vulnerability-oriented paths. "
        "Do not decide the final label. Do not hallucinate facts that are not supported by the code or paths. "
        "Focus on security-relevant sinks or validation points, data-flow sources, missing or existing checks, allocation/deallocation events, pointer dereference, array access, and arithmetic operations. "
        "Important: validation-related evidence is still real vulnerability-oriented evidence, even when no dangerous library API such as memcpy, strcpy, free, system, or printf is present. "
        "Do not state that the function definitely contains a vulnerability. Use cautious wording such as may indicate, potential risk, security-relevant evidence, or vulnerability-oriented evidence, because the final vulnerability label is determined by the classifier. Avoid over-confident statements such as lacks sufficient validation, no explicit bounds checking is present, or may lead to memory corruption unless the extracted evidence directly proves that claim. Prefer phrases such as the extracted evidence does not show complete validation, no explicit size-bound check is shown in the extracted evidence, or may require careful validation."
    )

    user_prompt = f"""
Please generate a security description for the following C/C++ function.

Evidence status:
{evidence_status}

Requirements:
1. Write in English.
2. Use 2 to 5 sentences.
3. Use only the given code and extracted paths. Do not infer facts that are not supported.
4. If Evidence status is HAS_REAL_VUL_PATH, do NOT write "no explicit rule-defined security-sensitive path is found".
5. If Evidence status is HAS_REAL_VUL_PATH and the path type is validation-related, describe it as "validation-related vulnerability-oriented evidence".
6. Mention the security-relevant sink or validation point if present.
7. Mention whether related checks are found.
8. Mention the possible vulnerability pattern, such as buffer overflow, integer overflow, out-of-bounds access, null pointer dereference, use-after-free, double free, format string, command injection, path traversal, resource leak, or validation-related integer boundary issue.
9. Do NOT write that the function definitely contains a vulnerability. Avoid phrases such as "the function contains a vulnerability" or "this is vulnerable". Use cautious wording such as "may indicate", "potential risk", "security-relevant evidence", or "vulnerability-oriented evidence".
10. Be conservative. Avoid over-confident phrases such as "lacks sufficient validation", "no explicit bounds checking is present", or "may lead to memory corruption" unless this is directly proven by the extracted evidence. Prefer "the extracted evidence does not show complete validation" or "may require careful validation".
11. If Evidence status is NO_REAL_VUL_PATH, say that no explicit rule-defined security-sensitive path is found, and do not claim the code is definitely safe.
12. Return only JSON in this format:
{{"security_desc": "..."}}

[Code]
{code}

[Extracted Vulnerability-Oriented Paths]
{vul_path_text}
""".strip()

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


# =============================
# API call
# =============================

def call_siliconflow_api(
    messages: List[Dict[str, str]],
    api_key: str,
    api_base_url: str,
    model: str,
    temperature: float = 0.1,
    max_tokens: int = 512,
    timeout: int = 60,
    retries: int = 3,
    sleep_seconds: float = 1.0,
) -> str:
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }

    last_error = None

    for attempt in range(1, retries + 1):
        try:
            resp = requests.post(
                api_base_url,
                headers=headers,
                json=payload,
                timeout=timeout,
            )

            if resp.status_code == 200:
                data = resp.json()
                return data["choices"][0]["message"]["content"]

            last_error = f"HTTP {resp.status_code}: {resp.text[:500]}"

        except Exception as e:
            last_error = str(e)

        if attempt < retries:
            time.sleep(sleep_seconds * attempt)

    raise RuntimeError(f"API call failed after {retries} retries. Last error: {last_error}")


def parse_security_desc(raw: str) -> str:
    raw = raw.strip()

    # Try direct JSON
    try:
        obj = json.loads(raw)
        desc = obj.get("security_desc", "")
        if desc:
            return clean_text(desc, max_chars=1800)
    except Exception:
        pass

    # Try extract JSON substring
    try:
        start = raw.find("{")
        end = raw.rfind("}")
        if start != -1 and end != -1 and end > start:
            obj = json.loads(raw[start:end + 1])
            desc = obj.get("security_desc", "")
            if desc:
                return clean_text(desc, max_chars=1800)
    except Exception:
        pass

    # Fallback: use raw response
    return clean_text(raw, max_chars=1800)



def postprocess_security_desc(desc: str, row: Dict[str, Any]) -> str:
    """
    Clean contradictory, over-confident, or too vulnerability-like LLM descriptions.

    Compared with v4, this v5 version fixes one wording bug:
    "potential out-of-bounds access vulnerability-oriented evidence"
    should not become "checked lower-risk out-of-bounds access evidence-oriented evidence".

    Goals:
    1. If real vul_path exists, remove wrong "no explicit path" statements.
    2. Convert confirmed-vulnerability language into evidence-based cautious language.
    3. Keep validation-related evidence explicit.
    4. For checked_or_lower_risk paths, use neutral wording and avoid making safe samples look too vulnerable.
    """
    desc = clean_text(desc, max_chars=1800)

    if not desc:
        return desc

    real_path = has_real_vul_path(row)

    if real_path:
        vul_path_text = clean_text(row.get("vul_path_text", ""), max_chars=4000).lower()
        is_validation_related = "integer_boundary_check_or_validation_logic" in vul_path_text
        is_checked_lower = "checked_or_lower_risk" in vul_path_text or "risk: checked_or_lower_risk" in vul_path_text

        # Remove contradictory no-evidence phrases.
        bad_no_evidence_phrases = [
            "No explicit rule-defined security-sensitive path is found.",
            "No explicit rule-defined security-sensitive path was found.",
            "No explicit rule-defined security-sensitive paths are found.",
            "No explicit vulnerability-oriented path is extracted.",
            "No vulnerability-oriented path is extracted.",
            "No explicit security-sensitive path is found.",
            "no explicit security-sensitive path is found.",
        ]

        for phrase in bad_no_evidence_phrases:
            desc = desc.replace(phrase, "")

        # First fix awkward phrases that may be produced by LLM itself.
        awkward_replacements = [
            (
                r"\bpotential out-of-bounds access vulnerability-oriented evidence\b",
                "security-relevant out-of-bounds access evidence",
            ),
            (
                r"\bout-of-bounds access vulnerability-oriented evidence\b",
                "out-of-bounds access evidence",
            ),
            (
                r"\bpotential vulnerability-oriented evidence\b",
                "security-relevant evidence",
            ),
            (
                r"\bvulnerability-oriented evidence-oriented evidence\b",
                "vulnerability-oriented evidence",
            ),
            (
                r"\bevidence-oriented evidence\b",
                "evidence",
            ),
            (
                r"\bThese validation-related vulnerability-oriented evidence suggests\b",
                "This validation-related vulnerability-oriented evidence suggests",
            ),
            (
                r"\bThese validation-related vulnerability-oriented evidence suggest\b",
                "This validation-related vulnerability-oriented evidence suggests",
            ),
        ]

        for pat, repl in awkward_replacements:
            desc = re.sub(pat, repl, desc, flags=re.IGNORECASE)

        # Replace over-confident vulnerability claims with cautious wording.
        replacements = [
            (
                r"\bThe function contains an out-of-bounds access vulnerability\b",
                "The extracted evidence may indicate an out-of-bounds access risk",
            ),
            (
                r"\bThe function contains a buffer overflow vulnerability\b",
                "The extracted evidence may indicate a buffer overflow risk",
            ),
            (
                r"\bThe function contains an integer overflow vulnerability\b",
                "The extracted evidence may indicate an integer overflow risk",
            ),
            (
                r"\bThe function contains a null pointer dereference vulnerability\b",
                "The extracted evidence may indicate a null pointer dereference risk",
            ),
            (
                r"\bThe function contains a use-after-free vulnerability\b",
                "The extracted evidence may indicate a use-after-free risk",
            ),
            (
                r"\bThe function contains a double-free vulnerability\b",
                "The extracted evidence may indicate a double-free risk",
            ),
            (
                r"\bThe function contains a format string vulnerability\b",
                "The extracted evidence may indicate a format string risk",
            ),
            (
                r"\bThe function contains a command injection vulnerability\b",
                "The extracted evidence may indicate a command injection risk",
            ),
            (
                r"\bThe function contains a path traversal vulnerability\b",
                "The extracted evidence may indicate a path traversal risk",
            ),
            (
                r"\bThe function contains a resource leak vulnerability\b",
                "The extracted evidence may indicate a resource-lifecycle risk",
            ),
            (
                r"\bThe function contains a vulnerability\b",
                "The extracted evidence may indicate a potential vulnerability risk",
            ),
            (
                r"\bThis function contains a vulnerability\b",
                "The extracted evidence may indicate a potential vulnerability risk in this function",
            ),
            (
                r"\bThis function is vulnerable\b",
                "This function contains security-relevant evidence that may indicate risk",
            ),
            (
                r"\bis vulnerable to\b",
                "may be exposed to",
            ),

            # Conservative weakening rules.
            (
                r"\black sufficient validation to prevent all edge cases\b",
                "may require careful validation for edge cases",
            ),
            (
                r"\blacks sufficient validation to prevent all edge cases\b",
                "may require careful validation for edge cases",
            ),
            (
                r"\black sufficient validation\b",
                "may not show complete validation in the extracted evidence",
            ),
            (
                r"\blacks sufficient validation\b",
                "may not show complete validation in the extracted evidence",
            ),
            (
                r"\bdoes not perform sufficient validation\b",
                "may not show complete validation in the extracted evidence",
            ),
            (
                r"\bdoes not validate sufficiently\b",
                "may not show complete validation in the extracted evidence",
            ),
            (
                r"\bNo explicit bounds checking is present\b",
                "No explicit size-bound check is shown in the extracted evidence",
            ),
            (
                r"\bNo explicit bounds check is present\b",
                "No explicit size-bound check is shown in the extracted evidence",
            ),
            (
                r"\bNo explicit bounds checking is found\b",
                "No explicit size-bound check is shown in the extracted evidence",
            ),
            (
                r"\bNo explicit bounds check is found\b",
                "No explicit size-bound check is shown in the extracted evidence",
            ),
            (
                r"\bwithout explicit bounds checking\b",
                "without an explicit size-bound check shown in the extracted evidence",
            ),
            (
                r"\bdoes not indicate a clear vulnerability path\b",
                "does not by itself confirm a vulnerability",
            ),
            (
                r"\bdo not indicate a clear vulnerability path\b",
                "do not by themselves confirm a vulnerability",
            ),
            (
                r"\bthe validation logic itself represents a potential vulnerability\b",
                "the validation logic is security-relevant and may require careful checking",
            ),
            (
                r"\bwhich may lead to memory corruption\b",
                "which could be relevant to memory-safety analysis if the surrounding code does not constrain the index",
            ),
            (
                r"\bwhich could lead to memory corruption\b",
                "which could be relevant to memory-safety analysis if surrounding constraints are insufficient",
            ),
            (
                r"\bmay lead to memory corruption\b",
                "may be relevant to memory-safety analysis if surrounding constraints are insufficient",
            ),
            (
                r"\bcould lead to memory corruption\b",
                "could be relevant to memory-safety analysis if surrounding constraints are insufficient",
            ),
        ]

        for pat, repl in replacements:
            desc = re.sub(pat, repl, desc, flags=re.IGNORECASE)

        # Avoid too decisive "indicates ... vulnerability" wording.
        desc = re.sub(
            r"\bindicates an? ([a-zA-Z\- ]+?) vulnerability\b",
            r"may indicate a \1 risk",
            desc,
            flags=re.IGNORECASE,
        )

        desc = re.sub(
            r"\bindicates ([a-zA-Z\- ]+?) vulnerabilities\b",
            r"may indicate \1 risks",
            desc,
            flags=re.IGNORECASE,
        )

        # For checked/lower-risk paths, rewrite risk phrases into neutral evidence phrases.
        if is_checked_lower:
            checked_replacements = [
                (
                    r"\bpotential out-of-bounds access risk\b",
                    "checked lower-risk out-of-bounds access evidence",
                ),
                (
                    r"\bout-of-bounds access risk\b",
                    "out-of-bounds access evidence",
                ),
                (
                    r"\bpotential vulnerability risk\b",
                    "security-relevant evidence that requires context",
                ),
                (
                    r"\bmay result in invalid memory access\b",
                    "may require checking against surrounding constraints",
                ),
                (
                    r"\bmay lead to accessing memory beyond the array bounds\b",
                    "may require confirming that surrounding constraints bound the array index",
                ),
                (
                    r"\bif 'i' exceeds the valid range\b",
                    "if surrounding constraints do not bound 'i'",
                ),
            ]

            for pat, repl in checked_replacements:
                desc = re.sub(pat, repl, desc, flags=re.IGNORECASE)

            # Add a neutral prefix if the description still sounds too strong.
            if "checked lower-risk" not in desc.lower():
                desc = "Checked lower-risk vulnerability-oriented evidence is extracted. " + desc

        # Make validation-related evidence explicit, but do not claim it is a confirmed bug.
        if is_validation_related:
            if "validation-related vulnerability-oriented evidence" not in desc.lower():
                desc = (
                    "Validation-related vulnerability-oriented evidence is extracted. "
                    + desc
                )

        # Final cleanup for awkward duplicate wording.
        final_replacements = [
            (
                r"\bchecked lower-risk out-of-bounds access evidence-oriented evidence\b",
                "checked lower-risk out-of-bounds access evidence",
            ),
            (
                r"\bchecked lower-risk out-of-bounds access evidence evidence\b",
                "checked lower-risk out-of-bounds access evidence",
            ),
            (
                r"\bevidence evidence\b",
                "evidence",
            ),
            (
                r"\brisk risk\b",
                "risk",
            ),
            (
                r"\bpotential potential\b",
                "potential",
            ),
        ]

        for pat, repl in final_replacements:
            desc = re.sub(pat, repl, desc, flags=re.IGNORECASE)

    else:
        # For no-evidence rows, keep it neutral.
        if "definitely safe" in desc.lower():
            desc = re.sub(
                r"\b(the code|this function|the function) is definitely safe\b",
                "no explicit rule-defined security-sensitive path is found",
                desc,
                flags=re.IGNORECASE,
            )

    # Clean double spaces caused by deletions and normalize punctuation spacing.
    desc = " ".join(desc.split())
    desc = desc.replace(" .", ".").replace(" ,", ",")

    return clean_text(desc, max_chars=1800)


# =============================
# Split processing
# =============================

def process_split(
    split: str,
    input_dir: str,
    output_dir: str,
    api_key: str,
    api_base_url: str,
    model: str,
    code_key: str,
    max_code_chars: int,
    max_path_chars: int,
    temperature: float,
    max_tokens: int,
    sleep_seconds: float,
    limit: int = -1,
):
    in_path = find_input_file(input_dir, split)

    if in_path is None:
        print(f"[Skip] Cannot find input file for split `{split}` in {input_dir}")
        return

    out_path = os.path.join(output_dir, f"{split}.desc.jsonl")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    rows = list(read_jsonl(in_path))
    if limit > 0:
        rows = rows[:limit]

    out_rows = []

    skipped_no_evidence = 0
    called_llm = 0

    for row in tqdm(rows, desc=f"Generating LLM descriptions for {split}"):
        out_row = dict(row)

        # Only call LLM when real vul_path evidence exists.
        # For <VUL_PATH> none </VUL_PATH>, do not call LLM and keep security_desc empty.
        if not has_real_vul_path(row):
            out_row["security_desc"] = ""
            out_row["security_desc_source"] = "no_real_vul_path_skipped"
            out_row["llm_raw_response"] = ""
            skipped_no_evidence += 1
            out_rows.append(out_row)
            continue

        try:
            messages = build_prompt(
                row=row,
                code_key=code_key,
                max_code_chars=max_code_chars,
                max_path_chars=max_path_chars,
            )

            raw = call_siliconflow_api(
                messages=messages,
                api_key=api_key,
                api_base_url=api_base_url,
                model=model,
                temperature=temperature,
                max_tokens=max_tokens,
                sleep_seconds=sleep_seconds,
            )

            called_llm += 1
            security_desc = parse_security_desc(raw)
            security_desc = postprocess_security_desc(security_desc, row)

            out_row["security_desc"] = security_desc
            out_row["security_desc_source"] = "siliconflow_llm"
            out_row["llm_raw_response"] = raw

        except Exception as e:
            fallback = (
                "LLM-based security description generation failed for this sample. "
                "The extracted vulnerability-oriented path should be used directly."
            )
            out_row["security_desc"] = fallback
            out_row["security_desc_source"] = "llm_failed"
            out_row["llm_error"] = str(e)

        out_rows.append(out_row)

        if sleep_seconds > 0:
            time.sleep(sleep_seconds)

    write_jsonl(out_path, out_rows)

    print(f"[Done] {split}: {len(out_rows)} samples")
    print(f"       input  -> {in_path}")
    print(f"       output -> {out_path}")
    print(f"       called LLM          : {called_llm}")
    print(f"       skipped no evidence : {skipped_no_evidence}")


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input_dir",
        type=str,
        required=True,
        help="Directory containing train.vul_paths.jsonl, valid.vul_paths.jsonl, test.vul_paths.jsonl",
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        required=True,
        help="Directory to save train.desc.jsonl, valid.desc.jsonl, test.desc.jsonl",
    )

    parser.add_argument(
        "--api_base_url",
        type=str,
        default=API_BASE_URL_DEFAULT,
    )

    parser.add_argument(
        "--model",
        type=str,
        default=API_MODEL_DEFAULT,
    )

    parser.add_argument(
        "--code_key",
        type=str,
        default="func",
        help="JSON key for source code. Default: func",
    )

    parser.add_argument(
        "--splits",
        type=str,
        default="train,valid,test",
    )

    parser.add_argument(
        "--max_code_chars",
        type=int,
        default=3500,
    )

    parser.add_argument(
        "--max_path_chars",
        type=int,
        default=2000,
    )

    parser.add_argument(
        "--temperature",
        type=float,
        default=0.1,
    )

    parser.add_argument(
        "--max_tokens",
        type=int,
        default=512,
    )

    parser.add_argument(
        "--sleep_seconds",
        type=float,
        default=0.3,
        help="Sleep time between API calls.",
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=-1,
        help="Only process first N samples for debugging. Default: -1 means all.",
    )

    args = parser.parse_args()

    api_key = os.getenv("SILICONFLOW_API_KEY", "").strip()

    if not api_key:
        raise ValueError(
            "SILICONFLOW_API_KEY is not set. "
            "Please set it as an environment variable instead of hard-coding it."
        )

    splits = [s.strip() for s in args.splits.split(",") if s.strip()]

    for split in splits:
        process_split(
            split=split,
            input_dir=args.input_dir,
            output_dir=args.output_dir,
            api_key=api_key,
            api_base_url=args.api_base_url,
            model=args.model,
            code_key=args.code_key,
            max_code_chars=args.max_code_chars,
            max_path_chars=args.max_path_chars,
            temperature=args.temperature,
            max_tokens=args.max_tokens,
            sleep_seconds=args.sleep_seconds,
            limit=args.limit,
        )


if __name__ == "__main__":
    main()
